<?php
/**
 *
 * @package wp-sanspapier
 */


if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_55b00186436cf',
  'title' => 'Modular content',
  'fields' => array (
    array (
      'key' => 'field_55b0018c7ded4',
      'label' => 'Flexible content',
      'name' => 'flexible_content',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Row',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '55b00198640c8',
          'name' => 'text_volle_breite',
          'label' => 'Text volle breite',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_55b001a67ded5',
              'label' => 'Titel',
              'name' => 'titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55b001b67ded7',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0, 
            ),
            array (
              'key' => 'field_55e330b36c018',
              'label' => 'External Link',
              'name' => 'link',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Bsp. "Weiterlesen", "Mehr Informationen"',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55e332726c028',
          'name' => 'text_volle_breite_dunkler_hintergrund',
          'label' => 'Text volle Breite dunkler Hintergrund',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55e332726c029',
              'label' => 'Titel',
              'name' => 'titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55e332726c02a',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_55e332726c02b',
              'label' => 'External Link',
              'name' => 'Link ',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Bsp. "Weiterlesen", "Mehr Informationen"',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55e88805fba5e',
          'name' => 'bild_2/3_breite_links_text_1/3_breite_rechts',
          'label' => 'Bild 2/3 Breite links Text 1/3 Breite rechts',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55e88805fba5f',
              'label' => 'Bild links',
              'name' => 'bild_links',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => 150,
              'mime_types' => '',
            ),
            array (
              'key' => 'field_55e94f473e97a',
              'label' => 'Box rechts Titel',
              'name' => 'box_rechts_titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55e94f6c3e97b',
              'label' => 'Box rechts Text',
              'name' => 'box_rechts_text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_55e94f8e3e97d',
              'label' => 'Box rechts Link',
              'name' => 'box_rechts_link',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55dad0ae1dc85',
          'name' => 'text_halbe_breite',
          'label' => 'Text halbe breite',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_55dad0d1d8fa2',
              'label' => 'Titel',
              'name' => 'titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
               'key' => 'field_55dc1929bb649',
               'label' => 'Icon',
               'name' => 'icon',
               'type' => 'image',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => array (
                 'width' => '',
                 'class' => '',
                 'id' => '',
               ),
               'return_format' => 'object',
               'preview_size' => 'thumbnail',
               'library' => 'all',
               'min_width' => '',
               'min_height' => '',
               'min_size' => '',
               'max_width' => '',
               'max_height' => '',
               'max_size' => 50,
               'mime_types' => '',
            ),
            array (
              'key' => 'field_55dad0dcd8fa3',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_55e331546c01e',
              'label' => 'Link: Weiterlesen',
              'name' => 'link_weiterlesen',
              'type' => 'url',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Weiterlesen',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
           ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55e334a7969bc',
          'name' => 'text_3/4_breite',
          'label' => 'Text 3/4 Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55e334a7969bd',
              'label' => 'Titel',
              'name' => 'titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55e334a7969be',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_55e334a7969bf',
              'label' => 'External Link',
              'name' => 'link',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Bsp. "Weiterlesen", "Mehr Informationen"',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55e331646c01f',
          'name' => 'text_2/3_breite',
          'label' => 'Text 2/3 Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55e331646c020',
              'label' => 'Titel',
              'name' => 'titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55e331646c022',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_55e331646c023',
              'label' => 'External Link',
              'name' => 'link',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Bsp. "Weiterlesen", "Mehr Informationen"',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55e331826c024',
          'name' => 'text_1/3_breite',
          'label' => 'Text 1/3 Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55e331826c025',
              'label' => 'Titel',
              'name' => 'titel',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55e331826c026',
              'label' => 'Text',
              'name' => 'text',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'basic',
              'media_upload' => 0,
            ),
            array (
              'key' => 'field_55e331826c027',
              'label' => 'External Link',
              'name' => 'link',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'Bsp. "Weiterlesen", "Mehr Informationen"',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55dad136d8fa5',
          'name' => 'bild_volle_breite',
          'label' => 'Bild volle Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55dad147d8fa6',
              'label' => 'Bild volle Breite',
              'name' => 'bild_volle_breite',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'object',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => 200,
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55dad1d2d8fa8',
          'name' => 'bild_halbe_breite',
          'label' => 'Bild halbe Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55dad1d2d8fa9',
              'label' => 'Bild halbe Breite',
              'name' => 'bild_halbe_breite',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'object',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => 200,
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ), 
        array (
          'key' => '55e412cf55a60',
          'name' => 'bild_23_breite',
          'label' => 'Bild 2/3 Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55e412cf55a61',
              'label' => 'Bild 2/3 Breite',
              'name' => 'bild_23_breite',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'object',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => 200,
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '55dad1d2d8fa8',
          'name' => 'bild_13_breite',
          'label' => 'Bild 1/3 Breite',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_55dad1d2d8fa9',
              'label' => 'Bild 1/3 Breite',
              'name' => 'bild_13_breite',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => 150,
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
));

endif;